services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./downloads:/app/downloads
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - APP_PASSWORD=admin             # 登录密码
      - GITHUB_URL=example.com        # 替换你的域名
    restart: always